export default {
    MSG: "SERVER_MESSAGE",
    ERR: "SERVER_ERROR_MESSAGE",
    SUCCESS: "SERVER_SUCCESS_MESSAGE",

    ERRORS: {
        ALREADY_IN_A_LOBBY: "ALREADY_IN_A_LOBBY",
        UNKNOWN_ERROR: "UNKNOWN_ERROR",
        LOBBY_DOESNT_EXIST: "LOBBY_DOESNT_EXIST",
        CONTROL_FIELD_LENGTHS: "CONTROL_FIELD_LENGTHS",
    },

    SUCCESS_MSGS: {
        CREATED_LOBBY: "CREATED_GAME_LOBBY",
        JOINED_LOBBY: "JOINED_GAME_LOBBY",
    },

    EVT: {
        CREATE_LOBBY: "CREATE_GAME_LOBBY",
        JOIN_LOBBY: "JOIN_GAME_LOBBY",
        GET_LOBBY_DATA_AFTER_CREATION: "GET_LOBBY_DATA_AFTER_CREATION",
        GET_LOBBY_DATA_AFTER_JOINING: "GET_LOBBY_DATA_AFTER_JOINING",
        PICK_NUMBER: "PICK_NUMBER",
        GET_PICKED_NUMBER: "GET_PICKED_NUMBER",
        NOTICE_NEW_PLAYER: "NOTICE_NEW_PLAYER",
        GAME_FINISHED: "GAME_FINISHED",
        GET_WINNER_DATA: "GET_WINNER_DATA",
    },

    LOBBY_PREFIX: "GAME_LOBBY:",
};
