export default {
    MSG: "SERVER_MESSAGE",
    ERR: "SERVER_ERROR_MESSAGE",
    SUCCESS: "SERVER_SUCCESS_MESSAGE",

    ERRORS: {
        LOBBY_EXISTS: "LOBBY_ALREADY_EXISTS",
        ALREADY_IN_A_LOBBY: "ALREADY_IN_A_LOBBY",
        UNKNOWN_LOBBY_CREATION_ERROR: "UNKNOWN_LOBBY_CREATION_ERROR",
    },

    SUCCESS_MSGS: {
        CREATED_LOBBY: "CREATED_GAME_LOBBY",
    },

    CREATE_LOBBY: "CREATE_GAME_LOBBY",
    LOBBY_PREFIX: "GAME_LOBBY:",
};
